services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network
    ports:
      - "5432:5432"
  cache:
    image: redis:latest
    networks:
      - db_network
    ports:
      - "6379:6379"
volumes:
  db_data:
    driver: local
networks:
  db_network:
    driver: bridge
